### PR TITLE
Removed react-native-dismiss-keyboard and fixed CI. Fixes #43

### LINKED ISSUE #43: react-native-dismiss-keyboard deprecated
The dependency react-native-dismiss-keyboard is deprecated in favour of the method dismiss() of the Keyboard component which comes within react-native.
https://facebook.github.io/react-native/docs/keyboard.html

### PR DESCRIPTION
**Pull request by raynor85**

### CODE REVIEW

**Review by DanielMSchmidt — CHANGES_REQUESTED** [review]
Hey, this looks great in general, good job 👍  The only thing I need to merge this is that we extend the table in the Readme which maps RN versions to versions of this library to exactly define from which RN version on you can use it with these changes (I will do a major release after this merge)

**Comment by raynor85** [comment]
Can you be more specific? I don't understand what is the correlation between the RN supported version and my modification I've made. Help me to help you :)
If you are asking which version of react native supports the new Keyboard.dismiss(), it is React Native >= 0.35, as suggested here: https://github.com/DanielMSchmidt/react-native-dismiss-keyboard

**Comment by DanielMSchmidt** [comment]
Hey, sure let me give you some context. 

The keyboard property was not always exposed by RN, so changing this would make this library incompatible with older RN versions which don't have this attribute. I would like to make that clear for users, that's why we have the little table with breaking changes

**Comment by raynor85** [comment]
Ok I get it. The problem is, if I change the table content, I also need to specify the bumped version related to the modification I made. I guess it should be marked as 2.0, but the versioning is really up to you. I could make another commit bumping the version to 2.0 and updating the README.md file with the information you are requesting, or you can update the README.md file yourself. As I said before, the React Native version which supports my modification is >= 0.35

**Comment by DanielMSchmidt** [comment]
Okay, I see your point. I'll merge it and document that myself. Thanks for
starting the right version already

**Pull request merged**
