### PR TITLE
RTL Support

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Unfortunately I needed to undo some changes necessary for device
orientation change support, sorry about that. I couldn't verify that the solution works with expo otherwise. @yuvalrakavy @satya164 @dastoori can you have a look at this?

@dastoori I will do a seperate PR for your Orientation Change detection, maybe you can test it on your iOS & Android devices afterwards, that would be great 👍

### CODE REVIEW

**Comment by satya164** [comment]
>  I couldn't verify that the solution works with expo otherwise

Why is that?

**Comment by DanielMSchmidt** [comment]
Because it's Dimensions don't have an addEventListener function.

**Comment by satya164** [comment]
Looking at the [commit which added the method](https://github.com/facebook/react-native/commit/186f308aecaac237ce89c2179a30a763fd986873), it was added in RN 0.43, so it should work if you are using latest expo (SDK 16)

**Comment by DanielMSchmidt** [comment]
I will check it out again. If it doesn't work I will just make it resilient to the absence of this feature. 👍

**Comment by DanielMSchmidt** [comment]
I will do a seperate PR on horizontal bugs in favor of shipping the RTL support, hope thats okay for y'all

**Comment by satya164** [comment]
NO IT IS NOT OKAY REVERT THIS NOW! xD

**Comment by DanielMSchmidt** [comment]
@satya164 seriously or did I miss the joke 😂

**Comment by satya164** [comment]
Just trolling you xD

**Comment by DanielMSchmidt** [comment]
You did sucessfully 😂

**Pull request merged**
