### PR TITLE
add accessibilityViewIsModal property

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This updates #5. @StefanoSarioli can you review this?

### CODE REVIEW

**Comment by stefano-sarioli** [comment]
Sure, 
I start working on this.

**Comment by DanielMSchmidt** [comment]
@StefanoSarioli I added the flowtypes now, can you check if this version works for you?

**Comment by stefano-sarioli** [comment]
Hey,
this is working for me, I just want to point out that accessibilityViewIsModal  is iOS only.
With this new implementation of the library we are no longer accessible by default  on Android  cause we are not using anymore the native android element, is this intentional?

Thanks for your hard work.
Stefano

**Comment by DanielMSchmidt** [comment]
Yes, it is intentional, the react-native-community/react-native-drawer-layout-polyfill is the project using the native android implementation

**Pull request merged**
